# Generated by Django 4.1.2 on 2022-10-28 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file_url',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
