# Generated by Django 4.0.3 on 2023-01-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_document_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.SmallIntegerField(choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')], default=1),
        ),
    ]
